### ISSUE TITLE
[FE] When no one answer survey in company/team show info rather then showing empty results and empty filters

### ISSUE THREAD

**Issue by tobob** [Selleo/team-fingerprints#443]
Setps to reproduce:
1. Create new account
2. Create company
3. Enter company details and 'Show results'
4. View any survey

<img width="1624" alt="Screenshot 2022-11-09 at 12 51 05" src="https://user-images.githubusercontent.com/3189332/200823758-f0cc7cd9-41df-45f2-9757-46a4c0647d5a.png">
<img width="1624" alt="Screenshot 2022-11-09 at 12 51 09" src="https://user-images.githubusercontent.com/3189332/200823764-d4e86231-6edb-4e04-bb9e-56ea4dd270c8.png">

Expected Behavior: It should show info 'No results for this survey'
Actual Behavior: It shows the results and filter sets with empty filters

**Comment by michaela559** [comment]
hello, can i work on this?

**Comment by tobob** [comment]
> hello, can i work on this?

@michaela559 I think that @typeWolffo already working on this ;)
