### ISSUE TITLE
[FE] Adding user by email with incorrect email adress

### ISSUE THREAD

**Issue by Matesty** [Selleo/team-fingerprints#473]
When adding user to the company by email, user should be not able to click on the "Add" button if provided email is incorrect

Actual results:
- User is able to click on the "Add" button, then modal is closed and no changes are made

Expected results:
- User should be informed that provided email is incorrect, or button should be grayed out

![image](https://user-images.githubusercontent.com/72445161/202163966-472b8d42-0831-4d52-8dbf-5071c75f2e3b.png)

**Comment by tobob** [comment]
related to https://github.com/Selleo/team-fingerprints/issues/440

**Comment by michaela559** [comment]
hello, so i understand this is fixed?

**Comment by Matesty** [comment]
@tobob fixed with https://github.com/Selleo/team-fingerprints/issues/439
