### ISSUE TITLE
[FE] Incorrect functioning of "Back to ..." button

### ISSUE THREAD

**Issue by shirve** [Selleo/team-fingerprints#513]
***Describe the bug:***

`Back to ...` button works incorrectly when used after using `Breadcrumbs`

***Steps To Reproduce:***

1. Open dropdown menu
2. Go to `Manage Roles and Companies`
3. Go to `Results` of your company
4. Choose any survey results
5. Use `Breadcrumbs` to go back to `Survey List`
6. Use `Back to ...` button to go back to `Company Management`

User gets navigated back to `Results`

***Expected behavior:*** 

User should be navigated to what the button says

**Comment by Matesty** [comment]
The same if not logged user will enter to the 'Check global results', he/she is not able to go back to the login page
