### ISSUE TITLE
[F/E] When answering survey and clicking Back button it go to previous question rather then to survey list

### ISSUE THREAD

**Issue by tobob** [Selleo/team-fingerprints#519]
***Describe the bug:***

When answering the survey and clicking the Back button it goes to the previous question rather than to survey list

***Steps To Reproduce:***

1. Open a fresh account
2. Start answering the survey
3. Answer a couple of questions
4. Click the back button inside the app

None/Irrelevant

It should go to the survey list

**Comment by Matesty** [comment]
@tobob fixed with https://github.com/Selleo/team-fingerprints/pull/517
