### ISSUE TITLE
[FE] Wrong button name in team managment

### ISSUE THREAD

**Issue by Matesty** [Selleo/team-fingerprints#536]
***Describe the bug:***

Wrong button name in the team managment while editing the team.
The name of the button should be the same like in other areas like this. 
E.g. in company edit

***Steps To Reproduce:***

1. Go to the /Team managment tab
2. Click on the 'Edit team' button
3. There will be "Send" button visible

***Expected behavior:*** 

The name of this button should be 'Update', like in the other areas

***Screenshots:***

![Zrzut ekranu_20221206_094650](https://user-images.githubusercontent.com/72445161/205893243-5c775873-ef3e-42bc-828b-352dc22cb922.png)

**Comment by shirve** [comment]
It's also wrong in Create new team as it's the same form for both create and update
