### ISSUE TITLE
Windows: Remove white scroll bar on main screen

### ISSUE THREAD

**Issue by tobob** [Selleo/team-fingerprints#574]
***Describe the bug:***

on the main screen there is a white scrollbar visible when the screen is too small - the height is not big enough

***Steps To Reproduce:***

1. Make the browser smaller
2. Clear cookies and local storage for teamfingerprints.selleo.com
3. Open page
4. Open one of the animations
5. Check right scrollbar

***Expected behavior:*** 

It should be less visible

None/Irrelevant

***Screenshots:***

![image (11)](https://user-images.githubusercontent.com/3189332/208864497-b9716b90-f87e-4462-bf84-6f289666b700.png)

***Desktop:***

 - OS: Windows
 - Browser: chrome

***Additional context:***

None/Irrelevant

**Comment by tobob** [comment]
@Matesty can you verify?

**Comment by Matesty** [comment]
One more place I have find, during creating a new survey:

![image](https://user-images.githubusercontent.com/72445161/210739899-8aefe201-984e-4544-a884-8a3a3b8365c4.png)

**Comment by DawidHaratyk** [comment]
> One more place I found, during creating a new survey:
> 
> ![image](https://user-images.githubusercontent.com/72445161/210739899-8aefe201-984e-4544-a884-8a3a3b8365c4.png)

I've changed that, can you check if it's okay?
