### ISSUE TITLE
Right after authentication there is a glitch that show Welcome Page for a sec

### ISSUE THREAD

**Issue by tobob** [Selleo/team-fingerprints#596]
***Describe the bug:***

Right after authentication there is a glitch that show Welcome Page for a sec

***Steps To Reproduce:***

1. Go to main page
2. Try to login
3. Durign login please check behavior of redirections
4. There is a 1sec glitch that show main WelcomePage

None/Irrelevant

***Expected behavior:*** 

There should not be any glitch and flickering

**Comment by Matesty** [comment]
Reproducible on any environment
