### ISSUE TITLE
B/E put information in profile about user skill,  year of exp..

### ISSUE THREAD

**Issue by tobob** [Selleo/team-fingerprints#93]

**Comment by Dariusz-Wylon** [comment]
while setting up profile user should provide such data as:

Tech Level: Junior, Independent, Middle, Senior
Country:
Company type: Software Development, Software Product, Other
Main Technology: Python, C, Java,  JavaScript, PHP, R, Go, Ruby, Rust, .Net, Scala, Mobile, DevOps, Testing, UX/UI, Business, Other

**Comment by tobob** [comment]
Country will be stored as ISO short string ISO 3166-1-alpha-2

https://www.npmjs.com/package/react-select-country-list

**Comment by tobob** [comment]
+ developer type: backend, frontend, devops
